run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  format: tab

linters-settings:
  varnamelen:
    min-name-length: 2
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - v

linters:
  enable-all: true
  disable:
    - golint
    - maligned
    - scopelint
    - interfacer
    - exhaustivestruct
    - wrapcheck
    - tagliatelle
    - noctx
    - bodyclose
